import type { Metadata } from "next";
import TheMenu from "@/components/home/TheMenu";
import { TopBar } from "@/components/home/TopBar";
import FooterBottomBar from "@/components/home/FooterBottomBar";
import ThePreFooter from "@/components/home/ThePreFooter";
import React from "react";
import {getServerSession} from "next-auth";
import {authOptions} from "@/app/api/auth/[...nextauth]/route";
import {redirect} from "next/navigation";

export const metadata: Metadata = {
    title: "Rainbow Roses",
    description: "Generated by create next app",
};

export default async function PublicLayout({
                                         children,
                                     }: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions);

    if (!session) {
        redirect("/login");
    }

    return (
        <>
            <TopBar/>
            <TheMenu/>
            {children}
            <div className="pl-4 py-8">
                <ThePreFooter/>
            </div>
            <div>
                <FooterBottomBar/>
            </div>
        </>
    );
}
