import type { Metadata } from "next";
import TheMenu from "@/components/home/TheMenu";
import { TopBar } from "@/components/home/TopBar";
import FooterBottomBar from "@/components/home/FooterBottomBar";
import ThePreFooter from "@/components/home/ThePreFooter";

export const metadata: Metadata = {
  title: "Rainbow Roses",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <TopBar/>
        <TheMenu/>
        {children}
        <div className="pl-4 py-8">
          <ThePreFooter/>
        </div>
        <div>
          <FooterBottomBar/>
        </div>
      </>
  );
}
